// Generated by CoffeeScript 1.3.3
(function() {
  var Colour;

  Colour = (function() {

    Colour.Default = new Colour([127, 127, 127, 1.0]);

    Colour.Black = new Colour([0, 0, 0, 1.0]);

    Colour.BasePlate = new Colour([32, 32, 32, 1.0]);

    Colour.BasePlateBorder = new Colour([64, 64, 64, 1.0]);

    Colour.Town = new Colour([0, 127, 255, 1.0]);

    Colour.Route = new Colour([127, 63, 0, 1.0]);

    Colour.Instance = new Colour([0, 255, 127, 1.0]);

    Colour.Obstacle = new Colour([0, 192, 0, 1.0]);

    Colour.Path = new Colour([63, 127, 63, 1.0]);

    Colour.RouteLink = new Colour([63, 31, 0, 1.0]);

    function Colour(_arg) {
      this.r = _arg[0], this.g = _arg[1], this.b = _arg[2], this.a = _arg[3];
      if (!this.a) {
        this.a = 1.0;
      }
    }

    Colour.prototype.rgba = function() {
      return "rgba(" + this.r + "," + this.g + "," + this.b + "," + this.a + ")";
    };

    return Colour;

  })();

  window.Colour = Colour;

}).call(this);
